<script>
  import { goto } from '$app/navigation'
  import { onMount } from 'svelte'
  import { config } from '$lib/config.svelte.js'
  import OcchialiDither from '$lib/components/OcchialiDither.svelte'

  let fase = $state('scorre')

  onMount(() => {
    setTimeout(() => {
      config.introFinita = true
      fase = 'home'
    }, 5000)
  })
</script>

{#if fase === 'scorre'}
  <div class="intro">
    <span class="intro-title">OFFRACE</span>
  </div>
{:else}
  <div class="home">

    <div class="riga-top">
      <div class="cella bordo-r">
        <h3 class="num-title">01_Performance</h3>
        <p>Performance is a word that belongs to the stage before it belongs to the slope. It has two lives: one as an artistic gesture, studied until it looks unstudied and natural; the other as a measurable output, a quantity generated by a system of interacting variables. Alpine skiing sits at the intersection of both. To spectators, it looks like pure physicality, it appears as a fluid motion and inevitable. But behind that flow lies a system of decisions made long before the descent begins: performance in alpine skiing isn't spontaneous, but a constructed act,  the product of environment, athlete, and equipment converging at the start gate.</p> 
      </div>
      <div class="cella">
        <h3 class="num-title">02_More than an athlete</h3>
        <p>There is a way of looking at an athlete that reduces them to quantities. A collection of data points that can be measured, tracked, improved and accumulated over years of preparation and expressed in a few minutes of competition.  A ski race runs on variables that can be configured in advance, chosen with precision, optimised for conditions that are known ahead of time. The athlete, in that moment, can only draw on what training has built. But the context around them  will play out regardless. It can amplify what the body is capable of. It can work against it. It operates on its own terms, indifferent to effort. This is what the configurator asks you to consider.</p>
      </div>
    </div>

    <div class="banda">
      <div class="marquee-track">
        {#each [1, 2, 3, 4] as i}
          <div class="marquee-item">
            <span>ENVIRONMENT</span>
            <span class="op">+</span>
            <span>ATHLETE</span>
            <span class="op">+</span>
            <span>EQUIPMENT</span>
            <span class="op">=</span>
            <span class="fluo">PERFORMANCE</span>
          </div>
        {/each}
      </div>
    </div>

    <div class="riga-bottom">

      <div class="cella bordo-r">
        <h3 class="num-title">03_Technodoping</h3>
        <p>It is a phenomenon whereby technological development in sport equipment had accelerated to a point where it was difficult possible to isolate the athlete's contribution from the machine's. Everything that happens inside the rules can still be unfair. This is the uncomfortable space that technodoping occupies, a grey zone where compliance and advantage coexist without contradiction. It also challenges the very concept of sport as something comparable, merit-based, and governable.</p>
      </div>

      <div class="cella-occhiali bordo-r">
        <OcchialiDither />
      </div>

      <div class="cella no-scroll">
        <h3 class="num-title">04_Regulations</h3>
        <p>The International Ski Federation's rules define the framework within which a race is run.</p>

        <div class="reg-list">
          <div class="reg-row">
            <span class="reg-num">1</span>
            <p>Gender-specific geometry requirements for ski length and turning radius</p>
          </div>
          <div class="reg-row">
            <span class="reg-num">2</span>
            <p>Constraints on core construction and composite materials.</p>
          </div>
          <div class="reg-row">
            <span class="reg-num">3</span>
            <p>Regulations on the type of wax that can be applied to the base</p>
          </div>
        </div>
      </div>

    </div>

  </div>

  <div class="bottom-bar">
    <div class="bb-spacer"></div>
    <button class="start-btn" onclick={() => goto('/athlete')}>
      START SIMULATION
    </button>
  </div>
{/if}

<style>
  /* ── INTRO ── */
  .intro {
    position: fixed;
    inset: 0;
    display: flex;
    align-items: center; 
    justify-content: flex-start;
    background: var(--mc-bg);
    overflow: hidden;
  }

  .intro-title {
    font-size: 125vh; 
    line-height: 0.72; 
    font-weight: 700;
    letter-spacing: -0.05em;
    white-space: nowrap;
    text-transform: uppercase;
    animation: scorra 5s linear forwards;
    color: black;
    margin: 0;
    padding: 0;
  }

  @keyframes scorra {
    0%   { transform: translateX(100vw); }
    100% { transform: translateX(-400vw); }
  }

  /* ── HOME ── */
  .home {
    position: fixed;
    top: 0;
    left: 0;
    right: 0;
    bottom: 76px; /* Lascia lo spazio esatto per la bottom bar */
    display: grid;
    grid-template-rows: auto auto 1fr;
    overflow: hidden;
    
    opacity: 0;
    animation: fadeIn 0.8s ease 0.8s forwards;
  }

  @keyframes fadeIn {
    from { opacity: 0; }
    to   { opacity: 1; }
  }

  .bordo-r { border-right: 1.5px solid black; }

  /* ── TIPOGRAFIA & DISTANZE ── */
  .num-title {
    font-size: clamp(1rem, 1.4vw, 1.25rem);
    font-weight: 800;
    letter-spacing: 0.02em;
    text-transform: uppercase;
    margin-bottom: 24px;
    margin-top: 0;
  }

  .cella p {
    font-size: 0.78rem;
    line-height: 1.6;
    color: #444;
    margin-bottom: 16px;
    margin-top: 0;
  }

  .cella p:last-child {
    margin-bottom: 0;
  }

  /* FASCIA ALTA */
  .riga-top {
    display: grid;
    grid-template-columns: 1fr 1fr;
    border-bottom: 1.5px solid black;
  }

  .riga-top .cella {
    padding: 40px;
  }

  /* ── BANDA MARQUEE ── */
  .banda {
    background: black; 
    color: white; 
    overflow: hidden; 
    padding: 24px 0; 
    border-bottom: 1.5px solid black;
    display: flex;
    align-items: center;
  }

  .marquee-track {
    display: flex;
    width: max-content;
    animation: marquee 30s linear infinite; /* <-- DIMEZZATA LA VELOCITÀ (da 15s a 30s) */
  }

  .marquee-item {
    display: flex;
    align-items: center;
    gap: 24px;
    padding-right: 48px; 
    font-size: clamp(1.1rem, 2.6vw, 2.5rem);
    font-weight: 800;
    letter-spacing: -0.02em;
    text-transform: uppercase;
    white-space: nowrap;
  }

  .marquee-item .op {
    font-weight: 400;
    opacity: 0.5;
  }

  .marquee-item .fluo {
    color: #BDF522;
  }

  @keyframes marquee {
    0% { transform: translateX(0); }
    100% { transform: translateX(-50%); } 
  }

  /* FASCIA BASSA */
  .riga-bottom {
    display: grid;
    grid-template-columns: 0.8fr 2fr 0.8fr;
    min-height: 0; 
    overflow: hidden;
  }

  .riga-bottom .cella {
    padding: 40px;
    height: 100%;
    overflow: hidden; 
  }

  .cella-occhiali {
    display: flex;
    align-items: center;
    justify-content: center;
    padding: 40px;
    position: relative;
    z-index: 5;
    height: 100%;
    overflow: hidden;
  }

  /* ── TABELLA REGULATIONS ── */
  .reg-list {
    margin-top: 24px;
    margin-left: -40px;
    margin-right: -40px;
    border-top: 1.5px solid black;
  }

  .reg-row {
    display: flex;
    gap: 24px;
    padding: 16px 40px; 
    border-bottom: 1.5px solid black;
  }

  .reg-row:last-child {
    border-bottom: none;
  }

  .reg-num {
    flex-shrink: 0;
    font-family: 'Geist Mono', monospace;
    font-weight: 700;
    font-size: 0.85rem;
    padding-top: 1px;
  }

  .reg-row p {
    font-size: 0.78rem;
    line-height: 1.6;
    color: #444;
    margin: 0;
    padding: 0;
  }

  /* ── BOTTOM BAR STYLES ── */
  .bottom-bar {
    position: fixed;
    bottom: 0;
    left: 0;
    right: 0;
    height: 76px;
    background: var(--mc-bg, #a02424);
    
    /* Linea nera sopra la bottom bar */
    border-top: 1.5px solid black; 
    
    display: grid;
    /* Stessa identica griglia della riga-bottom per allineare il pulsante */
    grid-template-columns: 0.8fr 2fr 0.8fr; 
    z-index: 50;
    opacity: 0;
    animation: fadeIn 0.8s ease 0.8s forwards;
    box-sizing: border-box;
  }

  .bb-spacer {
    /* Occupa le prime due colonne lasciandole vuote */
    grid-column: 1 / 3;
  }

  .start-btn {
    grid-column: 3 / 4;
    
    /* Resetta i bordi nativi del bottone e imposta solo quello sinistro */
    border: none;
    border-left: 1.5px solid black;
    border-radius: 0;
    outline: none;
    
    background: #BDF522;
    color: black;
    font-family: 'Geist Mono', monospace;
    font-size: 1rem;
    font-weight: 800;
    letter-spacing: 0.05em;
    cursor: pointer;
    display: flex;
    align-items: center;
    justify-content: center;
    transition: background 0.2s, color 0.2s;
    text-transform: uppercase;
    padding: 0;
    margin: 0;
  }

  .start-btn:hover {
    background: black;
    color: #BDF522;
  }
</style>